// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company info",
  description: "Get H & L Solutions LLC company overview: what they do, contact details, and how to request a free estimate.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "H & L Solutions LLC",
      focus: "Forestry mulching and land reclamation",
      phone: "256-749-5191",
      email: "hlsolutionsal@gmail.com",
      website: "https://hlsolutions.net",
      equipment: "Kubota SVL75-3 track loader with an Arthesis drum mulcher",
      estimates: "Free estimates. Call, text, or email with acreage, vegetation type, and site access."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var services = [
  { name: "Forestry Mulching", description: "Reclaim land in a single pass. No burning, no hauling." },
  { name: "Underbrush Clearing", description: 'Dense brush, saplings, and vegetation up to 6", cleared clean.' },
  { name: "Brush Hogging", description: "Mow down tall grass, weeds, and overgrown fields efficiently." },
  { name: "Property Line Clearing", description: "Precise boundary and fence row maintenance." },
  { name: "Fire Prevention", description: "Create defensible space and firebreaks around structures." },
  { name: "Trail Cutting", description: "Clean access paths through woods and fields." },
  { name: "Invasive Growth Removal", description: "Eliminate honeysuckle, briars, and invasive species." },
  { name: "Debris Removal", description: "Clear fallen limbs, brush piles, and land debris from your property." },
  { name: "Storm Clean Up", description: "Fast response to storm damage: downed trees, debris, and restoration." }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List the land clearing and forestry mulching services H & L Solutions LLC offers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/search-faq.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var faqs = [
  {
    question: "How much does forestry mulching cost?",
    answer: "Pricing is based on acreage, brush density, and terrain. We price by the project, day, or the hour to offer flexibility. Contact us for a free estimate."
  },
  {
    question: "How long will my project take?",
    answer: "Most residential projects are completed in 1-2 days. Larger or more complex jobs may take longer, but we provide a clear timeline during your quote."
  },
  {
    question: "Will your equipment damage my property?",
    answer: "Our machines use steel tracks that distribute weight evenly, minimizing ground disturbance. We take every precaution to protect your property."
  },
  {
    question: "Do you remove large trees?",
    answer: "We specialize in brush, saplings, and trees up to about 6 inches. For larger trees, we can pile to burn/haul away, or coordinate with licensed tree services for sensitive areas. We also offer grapple service to clean up any fallen or downed trees."
  },
  {
    question: "Will brush grow back?",
    answer: "Some regrowth is natural. To minimize it, many clients plant grass, clover, or wildflowers. We also offer guidance on spot-treating invasive roots."
  }
];
var search_faq_default = defineTool3({
  name: "search_faq",
  title: "Search FAQ",
  description: "Search the H & L Solutions FAQ about pricing, timelines, equipment, tree size limits, and regrowth. Omit the query to get every FAQ entry.",
  inputSchema: {
    query: z.string().optional().describe("Keywords to match against questions and answers.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const results = q ? faqs.filter((f) => (f.question + " " + f.answer).toLowerCase().includes(q)) : faqs;
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/index.ts
var SUPABASE_URL = "https://ptoenmzaqhhqhmwazhmt.supabase.co";
var mcp_default = defineMcp({
  name: "h-l-solutions",
  title: "H & L Solutions LLC",
  version: "0.1.0",
  instructions: "Public tools for H & L Solutions LLC, a forestry mulching and land reclamation company. Use `get_company_info` for contact details and estimates, `list_services` for the service catalog, and `search_faq` for common questions about pricing, timelines, and equipment.",
  // Require OAuth: callers must present a valid token issued by this project's
  // backend auth service, so only authenticated users can invoke tools.
  auth: auth.oauth.issuer({
    issuer: `${SUPABASE_URL}/auth/v1`,
    resource: `${SUPABASE_URL}/functions/v1/mcp`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_company_info_default, list_services_default, search_faq_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
